### ISSUE TITLE
problems with GroundHog

### ISSUE THREAD

**Issue by soloice** [DeepLearnXMU/VNMT#1]
Hi,

When I use the bleeding edge version of GroundHog, I met [this problem](https://github.com/lisa-groundhog/GroundHog/issues/53) . Have you ever encountered this issue?

My Theano version is `0.10.0beta3+129.ga44a3f8`. I don't know if it is due to the special Theano version.
Or, could you please share your pretrained and/or finetuned model?
Many thanks~

**Comment by bzhangGo** [comment]
@soloice I ran the code with Theano verison '0.9.0.dev-RELEASE' and found no problem. Maybe you can try this older version of Theano.

**Comment by soloice** [comment]
Oh, I see. I downgraded my numpy and Theano version, and the error above is gone.
But I'm now facing another issue, possibly related to my CUDA & cuDNN version.
So what's your CUDA and cuDNN version? Are you using CUDA 8.0 and cuDNN 5.1?
Thanks!

**Comment by bzhangGo** [comment]
Hi, I checked my CUDA & cuDNN. The version is the same as yours, CUDA 8.0 and CuDNN 5.1.

**Comment by soloice** [comment]
Thanks! I'm using cuDNN 7.0 and get a cuDNN compatibility error.
I guess I could fix this by downgrading cuDNN to version 5.1.

**Comment by soloice** [comment]
Thanks for your help. Theano and GroundHog is not maintained any more. Finally I decided to in modify [a TF reproduction of RNNSearch](https://github.com/XMUNLP/XMUNMT) and implement my own [VNMT](https://github.com/soloice/RNNsearch).
But I haven't reproduced the performance claimed in the VNMT paper yet. I'll continue working on this.
