### ISSUE TITLE
Is Equation 5 the *proper* ELBO of the likelihood P(Y|X)

### ISSUE THREAD

**Issue by hoangcuong2011** [DeepLearnXMU/VNMT#4]
Hello,

My last question from your paper: http://www.aclweb.org/anthology/D16-1050. I tried by myself to derive the ELBO of P(Y|X), but I couldn't come-up with any formula. Meanwhile, I found it indeed pretty easy/straightforward to derive the ELBO of P(Y, X), but not P(Y|X) indeed.

So I was wondering whether it is possible to derive ELBO of P(Y|X), or your formula (equation 5) is a kind of an approximation of ELBO instead?

Many thanks!

**Comment by bzhangGo** [comment]
I provide an **informal derivation** for the ELBO of P(Y|X) as follows:

The log-likelihood of this conditional generation is: log P(Y|X). After the integration of latent variable of z, it becomes:
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\log{P(Y|X)}=\log{\int_Z{P(Y,Z|X)}d_Z}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\log{\int_Z{P(Y|X,Z)P(Z|X)}d_Z}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\log{\mathop{\mathbb{E}}_{Z\sim{P(Z|X)}}{\left[P(Y|X,Z)\right]}}"/>
where P(Z|X) is the prior distribution of Z, and P(Y|X, Z) is the generation model where target sentence Y is generated by source sentence X together with the latent variable Z.

Suppose there is a distribution Q(Z) > 0, and put it into the above equation, we can get:
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\log{\int_Z{P(Y|X,Z)P(Z|X)}d_Z}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\log{\int_Z{\frac{P(Y|X,Z)P(Z|X)Q(Z)}{Q(Z)}}d_Z}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\log{\int_Z{\frac{P(Y|X,Z)P(Z|X)}{Q(Z)}Q(Z)}d_Z}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\log{\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\frac{P(Y|X,Z)P(Z|X)}{Q(Z)}}}"/>

Applying the JS inequality, we can get:
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad\geq\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\log\left[\frac{P(Y|X,Z)P(Z|X)}{Q(Z)}\right]}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\left\{\log{P(Y|X,Z)}+\log\left[\frac{P(Z|X)}{Q(Z)}\right]\right\}}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\log{P(Y|X,Z)}}-KL(Q(Z)||P(Z|X))"/>
where when Q(Z) approaches the true posterior distribution p(Z|X, Y), the lowerbound would be tight.

**Comment by AgoloCuongHoang** [comment]
Hi @bzhangGo : Thank you so much for your derivation. It makes sense.

I was just wondering last thing: let's call your final equation (the last line) is the ELBO. What is the gap between log P(Y|X) - ELBO?

I was asking because for P(X), we have P(X) = KL(q(z)||p(z|x)) + EBLO_{of P(X)} -> It is pretty clear the gap is KL(q(z)||p(z|x)). But I cannot find how to derive gap from your formua.
Again many thanks for your help!

Best,

**Comment by hoangcuong2011** [comment]
Hi @bzhangGo : Thank you so much for your derivation. It makes sense.

I was just wondering last thing: let's call your final equation (the last line) is the ELBO. What is the gap between log P(Y|X) - ELBO?

I was asking because for P(X), we have P(X) = KL(q(z)||p(z|x)) + EBLO_{of P(X)} -> It is pretty clear the gap is KL(q(z)||p(z|x)). But I cannot find how to derive such gap from your formula.
Again many thanks for your help!

Best,

**Comment by bzhangGo** [comment]
The gap is similar, for VNMT model, it is:

<img src="https://latex.codecogs.com/svg.latex?\Large&space;\log{P(Y|X)}=KL\left(Q(z)||p(z|x,y)\right)+ELBO"/>

In other words, it's the KL divergence between the true posterior and the approximated posterior.

Again, an **informal** derivation (perhaps have mistakes).

Notice the following equation,
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\log{P(Y|X)}=\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}\left(\log{P(Y|X)}\right)"/>

so,
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\log{P(Y|X)}-ELBO=\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}\left(\log{P(Y|X)}\right)-\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\left\{\log{P(Y|X,Z)}+\log\left[\frac{P(Z|X)}{Q(Z)}\right]\right\}}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\left\{\log{P(Y|X)}-\log{P(Y|X,Z)}-\log\left[\frac{P(Z|X)}{Q(Z)}\right]\right\}}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\log\left\{{\frac{P(Y|X)}{P(Y|X,Z)P(Z|X)}Q(Z)}\right\}}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\log\left\{{\frac{P(Y|X)}{P(Y,Z|X)}Q(Z)}\right\}}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\log\left\{{\frac{P(Y|X)}{P(Y|X)P(Z|X,Y)}Q(Z)}\right\}}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=\mathop{\mathbb{E}}_{Z\sim{Q(Z)}}{\log\left\{{\frac{Q(Z)}{P(Z|X,Y)}}\right\}}"/>
<img src="https://latex.codecogs.com/svg.latex?\Large&space;\rightarrow\qquad\quad=KL(Q(Z)||P(Z|X,Y))"/>

**Comment by hoangcuong2011** [comment]
Hello @bzhangGo : This is totally correct. I appreciate your time/patience a lot! Many thanks!
